modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
authors = "ganjamonsta, Daymix, 413XGreenwich"
credits = "Development: ganjamonsta; Textures: Daymix; Idea: 413XGreenwich"
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''TFC Advanced Drinks - Tea and Coffee (and more) addon for TerraFirmaCraft and Firmalife.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tfc"
    type="required"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="firmalife"
    type="required"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="coldsweat"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
